Implement query function
kyracq/step pull request #17
Opened 2020-07-13 22:43 UTC by kyracq

2020-07-13 23:40 UTC, shulijones approved these changes
LGTM! Seems really nice and clean.

2020-07-13 23:40 UTC, shulijones commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    for (int i = 1; i < invalidRanges.size(); i++) {
Could add another comment here describing your general strategy in this for loop

2020-07-13 23:40 UTC, shulijones commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        invalidRanges.add(event.getWhen());
I like the way you just work with TimeRange so you don't have to deal with Events.

2020-07-13 23:40 UTC, shulijones commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        if(validRange.duration() >= duration) {
Nit: space after if

2020-07-13 23:40 UTC, shulijones commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +      if(validRange.duration() >= duration) {
Nit: space after if

2020-07-14 01:18 UTC, otobin approved these changes
LGTM!

2020-07-14 01:39 UTC, anicr7 requested changes

2020-07-14 01:39 UTC, anicr7 commented on walkthroughs/week-5-tdd/intro/src/test/java/com/google/sps/GreeterTest.java
> +    String greeting = greeter.greet("@#$&*#Ada");
How about adding numbers here too?

2020-07-14 01:39 UTC, anicr7 commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +   * the of time ranges within which the meeting can be booked.
Remove

2020-07-14 01:39 UTC, anicr7 commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    int invalidRangeStart;
Simpler to use one-line for this instead of 4 different lines.

2020-07-14 01:39 UTC, anicr7 approved these changes

2020-07-14 19:59 UTC, nsri-google requested changes

2020-07-14 19:59 UTC, nsri-google commented on walkthroughs/week-5-tdd/intro/src/test/java/com/google/sps/GreeterTest.java
> +
You should also think about what are called "edge cases" so for example what if you pass the empty string or a string with empty spaces only.

2020-07-14 19:59 UTC, nsri-google commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    int invalidRangeStart;
I think the style guide recommends separate lines.

2020-07-14 19:59 UTC, nsri-google commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    if (invalidRanges.get(0).start() != TimeRange.START_OF_DAY) {
invalidRanges.get(0) is being used multiple times so it might be useful to store it in a variable

2020-07-14 19:59 UTC, nsri-google commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +      if (invalidRanges.get(i).start() > minInvalidRangeEnd) {
invalidRanges.get(i) is being used multiple times so it might be useful to store it in a variable

2020-07-14 19:59 UTC, nsri-google commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    for (int i = 1; i < invalidRanges.size(); i++) {
since you only care about the value and not the index (i) you could use the for each loop version (see method 2 in https://www.geeksforgeeks.org/iterating-arraylists-java/).

2020-07-14 19:59 UTC, nsri-google commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        TimeRange validRange = TimeRange.fromStartEnd(validRangeStart, validRangeEnd, false);
The same sequence of steps is done in multiple places, maybe you should have a helper function for it.

2020-07-14 20:40 UTC, kyracq commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    for (int i = 1; i < invalidRanges.size(); i++) {
I did consider using a for each loop however I needed to start at index 1, so I thought I'd be simpler to use a regular for loop where I can set i to start at 1.

2020-07-14 20:59 UTC, nsri-google approved these changes

2020-07-14 21:04 UTC, merged